name: ahio
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  hexcolor: ^3.0.1
  pin_code_fields: ^7.4.0
  flutter_walkthrough_screen: ^2.0.2
  animated_splash_screen: ^1.3.0
  onboard: ^1.0.1
  salomon_bottom_bar: ^3.3.1
  custom_radio_grouped_button: ^2.1.2+2
  image_picker: ^1.0.6
  shared_preferences: ^2.2.2
  http: ^1.1.2
  flutter_map: ^6.1.0
  sliding_up_panel: ^2.0.0+1
  geolocator: ^10.1.0
  flutter_map_location_marker: ^8.0.3
  location: ^5.0.3
  dropdown_search: ^5.0.5
  sizer: ^2.0.15
  intl_phone_number_input: ^0.7.3+1
  gap: ^3.0.1
  auto_size_text: ^3.0.0
  percent_indicator: ^4.2.3
  datepicker_dropdown: ^0.0.7+4
  syncfusion_flutter_datepicker: ^21.2.3
  path_provider: ^2.0.7
  dotted_border: ^2.1.0
  intl: ^0.18.1
  google_fonts: ^6.1.0
  http_parser: ^4.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.1
  build_runner:
  flutter_gen_runner:

flutter:
  uses-material-design: true

  assets:
    - images/
