name: ahio
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.18.5 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  hexcolor: ^3.0.1
  pin_code_fields: ^7.4.0
  flutter_walkthrough_screen: ^2.0.2
  animated_splash_screen: ^1.3.0
  onboard: ^1.0.1
  salomon_bottom_bar: ^3.3.1
  custom_radio_grouped_button: ^2.1.2+2
  image_picker: ^1.0.2
  shared_preferences: ^2.0.17
  http: ^0.13.5
  flutter_map: ^3.1.0
  sliding_up_panel: ^2.0.0+1
  geolocator: ^9.0.2
  flutter_map_location_marker: ^5.2.0+2
  location: ^4.4.0
  dropdown_search: ^5.0.5
  sizer: ^2.0.15
  intl_phone_number_input: ^0.7.2
  gap: ^3.0.1
  auto_size_text: ^3.0.0
  percent_indicator: ^4.2.3
  datepicker_dropdown: ^0.0.7+4
  syncfusion_flutter_datepicker: ^21.1.41
  path_provider: ^2.0.7
  dotted_border: ^2.0.0+3
  intl: ^0.18.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  build_runner:
  flutter_gen_runner:

flutter:
  uses-material-design: true

  assets:
    - images/